images/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += [
    url(r'', include('photos.urls', namespace='photos')),
]

photos/urls.py
from django.conf.urls import url

from .views import (HomepageView, PhotoCreateView, PhotoDeleteView,
                    PhotoDetailView)


urlpatterns = [
    url(r'^detail/(?P<pk>\d+)/(?P<slug>[\w\d_-]+)/$',
        PhotoDetailView.as_view(),
        name='detail_photo'),
    url(r'^create/$', PhotoCreateView.as_view(), name='create_photo'),
    url(r'^delete/(?P<pk>\d+)/$',
        PhotoDeleteView.as_view(),
        name='delete_photo'),
    url(r'^$', HomepageView.as_view(), name='homepage'),
]

photos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from jsonfield import JSONField

from image_cropping import ImageRatioField

from .utils import get_visual_report


class Photo(models.Model):
    """Photo model stores image file."""

    title = models.CharField(_('Title'), max_length=150)
    created_date = models.DateTimeField(
        _('Created date'), default=timezone.now)
    image = models.ImageField(_('Image'), upload_to='photos')
    cropping = ImageRatioField(
        'image', '600x600', size_warning=True,
        verbose_name=_('Photo cropping'))
    visual_report = JSONField(blank=True, null=True)
    slug = models.SlugField(
        _('Slug'),
        help_text=_('it\'s a string, which is shown in url address'),
        blank=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Photo')
        verbose_name_plural = _('Photos')
        ordering = ('-created_date',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Photo, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('photos:detail_photo',
                            kwargs={'pk': self.pk, 'slug': self.slug})

    def report_labels(self):
        try:
            return self.visual_report['responses'][0]['labelAnnotations']
        except:
            return None


@receiver(post_save, sender=Photo)
def vision_analysis(sender, **kwargs):
    """Connect with google vision api and receives visual report."""
    instance = kwargs['instance']
    instance_query = Photo.objects.filter(pk=instance.pk)
    try:
        visual_report = get_visual_report(instance.image)
        instance_query.update(visual_report=visual_report)
    except:
        pass

photos/views.py
from django.views.generic import ListView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .models import Photo


class HomepageView(ListView):
    """HomepageView displays photos list and menu."""
    model = Photo
    template_name = 'photos/homepage.html'


class PhotoDetailView(DetailView):
    model = Photo


class PhotoCreateView(CreateView):
    """PhotoCreateView creates new photo object."""
    model = Photo
    fields = ['title', 'image']


class PhotoDeleteView(DeleteView):
    """PhotoDeleteView removes photo object."""
    model = Photo
    success_url = reverse_lazy('photos:homepage')

photos/templates/photos/homepage.html
{% extends 'base.html' %}

{% load i18n %}
{% load cropping %}

{% block content %}
<div class="container">
    <div class="row">
        {% for photo in object_list %}
        <div class="col-md-4">
            <div class="thumbnail">
                <a href="{{ photo.get_absolute_url }}" target="_blank">
                    <div class="caption"><p>{{ photo.title }}</p></div>
                    <img src="{% cropped_thumbnail photo 'cropping' %}" alt="{{ photo.title }}" style="width:100%">
                    <div class="caption">
                        <form action="{% url 'photos:delete_photo' pk=photo.pk %}"
                              method="post"
                              onsubmit='return confirm("{% blocktrans with photo_title=photo.title %}Do you really want to delete the photo \"{{ photo_title }}\"?{% endblocktrans %}");''>
                            {% csrf_token %}
                            <input type="submit" value="{% trans 'Delete' %}" class="btn btn-default" />
                        </form>
                  </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

photos/templates/photos/photo_detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load photos_tags %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h2>{{ object.title }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        <img src="{{ object.image.url }}" class="img-responsive">
    </div>
    <div class="col-sm-4">
        {% if object.report_labels %}
            <h3>Vision​ ​analysis</h3>
            {% for label in object.report_labels %}
                <p>{{ label.description }}</p>
                 <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="{{ label.score|percentage }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ label.score|percentage }}">
                    {{ label.score|percentage }}
                    </div>
                </div>
                </tr>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

photos/templates/photos/photo_form.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<div class="container">
    <h2>Create new photo</h2>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                <label class="control-label col-sm-2">{{ field.label_tag }}</label>
                <div class="col-sm-10 form-control-file">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="{% trans 'Save' %}" class="btn btn-default" />
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/_header.html
{% load i18n %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a class="navbar-brand active" href="/">{% trans "Images" %}</a></li>
            <li><a href="{% url 'photos:create_photo' %}">{% trans 'Add photo' %}</a></li>
        </ul>
    </div>
</nav>

templates/base.html
{% load static i18n %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Images hosting page{% endblock %}</title>

        <!-- og tags-->
        <meta property=”og:title” content="{% trans 'Images hosting' %}" />

        {% block extra_css %}{% endblock %}
         <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>  
    </head>
    <body>
            {% block page_header %}
                {% include "_header.html" %}
            {% endblock %}
            {% block content %}{% endblock %}
            {% block page_footer %}{% endblock %}
            {% block extra_js %}{% endblock %}
    </body>
</html>